# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - nikolaevairman@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always
env:
  global:
    - CODECOV_TOKEN="ab56e8bd-4b9e-483f-98d5-d9760f45504b"